elasticsearch:
  load:
    index_name: "health_data"
    settings:
      index:
        number_of_shards: 1
        number_of_replicas: 0
      analysis:
        analyzer:
          health_analyzer:
            type: custom
            tokenizer: standard
            filter: ["lowercase", "stop", "snowball"]
    mappings:
      dynamic: true
      properties:
        patient_id: {type: keyword}
        patient_name: {type: text, analyzer: health_analyzer}
        diagnosis: {type: text}
        visit_date: {type: date}
        billing_amount: {type: float}