gmail_pipeline:
  extraction:
    query: "is:unread"
    batch_size: 10
    fields: 
      - "subject"
      - "from"
      - "date"
    extraction_mode: "full"

  transformation:
    index_name: "gmail_index"
    textractor:
      paragraphs: true
      sections: true
    segmentation:
      sentences: true
      minlength: 20
      maxlength: 512
    
  load:
    index_name: "gmail_index" # Loader uses this to create/verify the index