spark:
  app_name: "S3SparkConnector"
  packages:
    - "org.apache.hadoop:hadoop-aws:3.3.4"
    - "com.amazonaws:aws-java-sdk-bundle:1.12.262"
    - "org.elasticsearch:elasticsearch-spark-30_2.12:8.15.1"

extractor:
  path: "s3a://data-engineering-bucket-s3/tiny_commerce.csv"
  format: "csv"
  batch_size_mb: 20
  options:
    header: true
    inferSchema: true
    delimiter: ","

transformation:
  id_column: "" 

embedding:
  model_name: "all-MiniLM-L6-v2"
  output_column: "row_vector"
  checkpoint_path: "file:///home/logi/github/alphaesai/aiplatform/static/health_data/embedder"

elasticsearch:
  host: "localhost"
  port: 9200
  index_name: "sales_data"
  write_mode: "append"
  vector_column: "row_vector"
  checkpoint_path: "file:///home/logi/github/alphaesai/aiplatform/static/health_data/embedder"
  settings:
    index:
      number_of_shards: 1
      number_of_replicas: 0
      refresh_interval: "-1"  # Disable background refreshes during ingestion
  mappings:
    properties:
      id: {type: "keyword"}
      text: {type: "text"}
      row_vector: {type: "dense_vector", dims: 384}
      metadata: {type: "object"}